modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="tinkers_tetra"
version="0.0.1-1.18.2"
displayName="Tinkers' Tetra"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/orgs/Team-Octobros/repositories"
logoFile="t_tmodlogo.png"
credits="To our devs and supporters, thank you"
authors="Team Octoboros"
description='''
Tinkers' Tetra is a compatability and integration mod for Tinkers' Construct & Tetra!

Focusing on modded material used on both sides in a balanced way, as to bring Tinkers Construct & Tetra a bit closer.

Currently in Alpha 0.0.1-1.18.2
'''

[[dependencies.tinkers_tetra]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tinkers_tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
